openapi: 3.0.0
info:
  title: Notion API
  description: "Hello and welcome!\n\nTo make use of this API collection collection as it's written."
  version: 1.0.0
servers:
  - url: https://api.notion.com
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
tags:
  - name: Users
    description: >-
      All actions in a Notion workspace are associated to a
      [user](https://developers.notion.com/reference/user), whether it be a bot
      via a [Notion
      integration](https://developers.notion.com/docs/getting-started) or a
      person interacting with Notion's UI.


      These endpoints allow developers to interact with users programmatically
      by [listing all users](https://developers.notion.com/reference/get-user),
      [retrieving information about your integration's
      bot](https://developers.notion.com/reference/get-self), or [retrieving a
      specific user](https://developers.notion.com/reference/get-user) in your
      Notion workspace.


      To learn more, read [Notion's official
      documentation](https://developers.notion.com/reference/user) for endpoints
      related to users.
  - name: Databases
    description: >-
      Databases represent collections of Notion pages that can be
      [sorted](https://developers.notion.com/reference/post-database-query-sort)
      and
      [queried](https://developers.notion.com/reference/post-database-query).
      Each database will have a schema (or properties) that represent the
      columns in the database table. Notion offers several types of properties,
      as described in the [official
      documentation](https://developers.notion.com/reference/property-object).


      These database-related endpoints allow developers to work with databases
      programmatically by
      [creating](https://developers.notion.com/reference/create-a-database),
      [retrieving](https://developers.notion.com/reference/retrieve-a-database),
      and [updating](https://developers.notion.com/reference/update-a-database)
      them.


      To learn more, read [Notion's official
      documentation](https://developers.notion.com/reference/database) for
      endpoints related to databases. We also recommend reading the official
      Notion guide for [working with
      databases](https://developers.notion.com/docs/working-with-page-content).
  - name: Pages
    description: >-
      Pages represent documents in Notion workspaces that can be created in a
      workspace directly or organized within in a Notion database.


      These page-related endpoints allow developers to work with pages
      programmatically by
      [creating](https://developers.notion.com/reference/post-page),
      [retrieving](https://developers.notion.com/reference/retrieve-a-page),
      [updating](https://developers.notion.com/reference/patch-page), and
      [archiving](https://developers.notion.com/reference/archive-a-page) them.


      To learn more, read [Notion’s official
      documentation](https://developers.notion.com/reference/page) for endpoints
      related to pages. We also recommend reading the official Notion guide for
      [working with page
      content](https://developers.notion.com/docs/working-with-page-content).
  - name: Blocks
    description: >-
      A block represents a piece of content in a Notion workspace. All Notion
      pages are composed of a series of blocks. Blocks can vary in type,
      including (but not limited to) headers, styled text, images, tables, and
      more. To see a complete list of block types, refer to Notion’s [official
      documentation](https://developers.notion.com/reference/page-property-values#type-objects).


      These block-related endpoints allow developers to work with blocks
      programmatically by
      [creating](https://developers.notion.com/reference/patch-block-children),
      [retrieving](https://developers.notion.com/reference/retrieve-a-block),
      [updating](https://developers.notion.com/reference/update-a-block), and
      [deleting](https://developers.notion.com/reference/delete-a-block) them
      from Notion pages.


      To learn more, read [Notion’s official
      documentation](https://developers.notion.com/reference/block) for
      endpoints related to blocks. We also recommend reading the official Notion
      guides for [working with page
      content](https://developers.notion.com/docs/working-with-page-content)
      (a.k.a. blocks) and [working with files and
      media](https://developers.notion.com/docs/working-with-files-and-media).
  - name: Search
    description: >-
      Search all pages and databases shared with your Notion integration. To
      learn more, read Notion’s [official
      documentation](https://developers.notion.com/reference/post-search) for
      the Public API endpoints.
  - name: Comments
    description: >-
      [Comments](https://developers.notion.com/reference/comment-object) can be
      added to a page or inline (i.e., to blocks).  

      These comment-related endpoints allow developers to work with comments
      programmatically by
      [creating](https://developers.notion.com/reference/create-a-comment) and
      [retrieving](https://developers.notion.com/reference/retrieve-a-block)
      them.  
        
      To learn more, read [Notion’s official
      documentation](https://developers.notion.com/reference/comment-object) for
      endpoints related to comments. We also recommend reading the official
      Notion guide for [working with
      comments](https://developers.notion.com/docs/working-with-comments).
paths:
  
  /v1/databases/{id}:
    get:
      tags:
        - Databases
      summary: Retrieve a database
      description: 'Retrieves a database object using the ID specified in the request path. '
      parameters:
        - name: Notion-Version
          in: header
          schema:
            type: string
          example: '{{NOTION_VERSION}}'
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: '{{DATABASE_ID}}'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              
    patch:
      tags:
        - Databases
      summary: Update database properties
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                properties:
                  Wine Pairing:
                    name: New Property Name
      parameters:
        - name: Notion-Version
          in: header
          schema:
            type: string
          example: '{{NOTION_VERSION}}'
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: '{{DATABASE_ID}}'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              examples:
                
  /v1/databases/{id}/query:
    post:
      tags:
        - Databases
      summary: Filter a database
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: >-
                "{\n    \"filter\": {\n        \"property\":
                \"Status\",\n        \"select\": {\n            \"equals\":
                \"Reading\"\n        }\n    }\n}"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer secret_t1CdN9S8yicG5eWLUOfhcWaOscVnFXns
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: Notion-Version
          in: header
          schema:
            type: string
          example: '{{NOTION_VERSION}}'
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: '{{DATABASE_ID}}'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              
                
  /v1/databases/:
    post:
      tags:
        - Databases
      summary: Create a database
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: >-
                "{\n    \"parent\": {\n        \"type\": \"page_id\",\n       
                \"page_id\": \"{{PAGE_ID}}\"\n    },\n    \"title\": [\n       
                {\n            \"type\": \"text\",\n            \"text\":
                {\n                \"content\": \"Grocery
                List\",\n                \"link\": null\n            }\n       
                }\n    ],\n    \"properties\": {\n        \"Name\":
                {\n            \"title\": {}\n        },\n       
                \"Description\": {\n            \"rich_text\": {}\n       
                },\n        \"In stock\": {\n            \"checkbox\":
                {}\n        },\n        \"Food group\": {\n           
                \"select\": {\n                \"options\":
                [\n                    {\n                        \"name\":
                \"🥦Vegetable\",\n                        \"color\":
                \"green\"\n                    },\n                   
                {\n                        \"name\":
                \"🍎Fruit\",\n                        \"color\":
                \"red\"\n                    },\n                   
                {\n                        \"name\":
                \"💪Protein\",\n                        \"color\":
                \"yellow\"\n                    }\n               
                ]\n            }\n        },\n        \"Price\": {\n           
                \"number\": {\n                \"format\":
                \"dollar\"\n            }\n        },\n        \"Last ordered\":
                {\n            \"date\": {}\n        },\n        \"Store
                availability\": {\n            \"type\":
                \"multi_select\",\n            \"multi_select\":
                {\n                \"options\": [\n                   
                {\n                        \"name\": \"Duc Loi
                Market\",\n                        \"color\":
                \"blue\"\n                    },\n                   
                {\n                        \"name\": \"Rainbow
                Grocery\",\n                        \"color\":
                \"gray\"\n                    },\n                   
                {\n                        \"name\": \"Nijiya
                Market\",\n                        \"color\":
                \"purple\"\n                    },\n                   
                {\n                        \"name\": \"Gus's Community
                Market\",\n                        \"color\":
                \"yellow\"\n                    }\n               
                ]\n            }\n        },\n        \"+1\": {\n           
                \"people\": {}\n        },\n        \"Photo\": {\n           
                \"files\": {}\n        }\n    }\n}"
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: Notion-Version
          in: header
          schema:
            type: string
          example: '{{NOTION_VERSION}}'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                object: database
                id: 23cde96c-0ad8-41d8-bfa2-b477c63dd52a
                cover: null
                icon: null
                created_time: '2022-02-24T22:06:00.000Z'
                created_by:
                  object: user
                  id: 92a680bb-6970-4726-952b-4f4c03bff617
                last_edited_by:
                  object: user
                  id: 92a680bb-6970-4726-952b-4f4c03bff617
                last_edited_time: '2022-02-24T22:06:00.000Z'
                title:
                  - type: text
                    text:
                      content: Grocery List
                      link: null
                    annotations:
                      bold: false
                      italic: false
                      strikethrough: false
                      underline: false
                      code: false
                      color: default
                    plain_text: Grocery List
                    href: null
                properties:
                  Description:
                    id: '%3EWW~'
                    name: Description
                    type: rich_text
                    rich_text: {}
                  Last ordered:
                    id: O%5C%3BK
                    name: Last ordered
                    type: date
                    date: {}
                  In stock:
                    id: Pya%5C
                    name: In stock
                    type: checkbox
                    checkbox: {}
                  '+1':
                    id: '%5CSky'
                    name: '+1'
                    type: people
                    people: {}
                  Photo:
                    id: dSrT
                    name: Photo
                    type: files
                    files: {}
                  Store availability:
                    id: jRd%3E
                    name: Store availability
                    type: multi_select
                    multi_select:
                      options:
                        - id: 8e6441ee-8f17-4833-a2fe-68af5dced24f
                          name: Duc Loi Market
                          color: blue
                        - id: 64a9da77-9805-461f-9773-1e176fdbd203
                          name: Rainbow Grocery
                          color: gray
                        - id: 012d0436-66a1-4613-a1bd-314b1d1d059b
                          name: Nijiya Market
                          color: purple
                        - id: 63ab31f9-8cbd-4d02-8688-752376f455ea
                          name: Gus's Community Market
                          color: yellow
                  Food group:
                    id: q%5DO%5B
                    name: Food group
                    type: select
                    select:
                      options:
                        - id: 392af858-f42f-43ea-a171-7c0ca5c0a683
                          name: 🥦Vegetable
                          color: green
                        - id: df461a24-14c6-494a-8c61-55775fedbdcd
                          name: 🍎Fruit
                          color: red
                        - id: 0ff22aaa-348e-4194-83c2-67a76dfb10fc
                          name: 💪Protein
                          color: yellow
                  Price:
                    id: t%60jj
                    name: Price
                    type: number
                    number:
                      format: dollar
                  Name:
                    id: title
                    name: Name
                    type: title
                    title: {}
                parent:
                  type: page_id
                  page_id: c4d39556-6364-46a1-8a61-ebbb668f7445
                url: https://www.notion.so/23cde96c0ad841d8bfa2b477c63dd52a
                archived: false
  /v1/pages/:
    post:
      tags:
        - Pages
      summary: Create a page with content
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: >-
                "{\n    \"parent\": {\n        \"database_id\":
                \"{{DATABASE_ID}}\"\n    },\n    \"properties\": {\n       
                \"Type\": {\n            \"select\": {\n                \"id\":
                \"f96d0d0a-5564-4a20-ab15-5f040d49759e\",\n               
                \"name\": \"Article\",\n                \"color\":
                \"default\"\n            }\n        },\n        \"Score /5\":
                {\n            \"select\": {\n                \"id\":
                \"5c944de7-3f4b-4567-b3a1-fa2c71c540b6\",\n               
                \"name\": \"⭐️⭐️⭐️⭐️⭐️\",\n                \"color\":
                \"default\"\n            }\n        },\n        \"Name\":
                {\n            \"title\": [\n               
                {\n                    \"text\": {\n                       
                \"content\": \"New Media Article\"\n                   
                }\n                }\n            ]\n        },\n       
                \"Status\": {\n            \"select\": {\n               
                \"id\":
                \"8c4a056e-6709-4dd1-ba58-d34d9480855a\",\n               
                \"name\": \"Ready to Start\",\n                \"color\":
                \"yellow\"\n            }\n        },\n        \"Publisher\":
                {\n            \"select\": {\n                \"id\":
                \"01f82d08-aa1f-4884-a4e0-3bc32f909ec4\",\n               
                \"name\": \"The Atlantic\",\n                \"color\":
                \"red\"\n            }\n        },\n        \"Publishing/Release
                Date\": {\n            \"date\": {\n                \"start\":
                \"2020-12-08T12:00:00Z\",\n                \"end\":
                null\n            }\n        },\n        \"Link\":
                {\n            \"url\":
                \"https://www.nytimes.com/2018/10/21/opinion/who-will-teach-silicon-valley-to-be-ethical.html\"\n       
                },\n        \"Summary\": {\n            \"rich_text\":
                [\n                {\n                    \"type\":
                \"text\",\n                    \"text\":
                {\n                        \"content\": \"Some think chief
                ethics officers could help technology companies navigate
                political and social questions.\",\n                       
                \"link\": null\n                    },\n                   
                \"annotations\": {\n                        \"bold\":
                false,\n                        \"italic\":
                false,\n                        \"strikethrough\":
                false,\n                        \"underline\":
                false,\n                        \"code\":
                false,\n                        \"color\":
                \"default\"\n                    },\n                   
                \"plain_text\": \"Some think chief ethics officers could help
                technology companies navigate political and social
                questions.\",\n                    \"href\":
                null\n                }\n            ]\n        },\n       
                \"Read\": {\n            \"checkbox\": false\n        }\n   
                },\n    \"children\": [\n        {\n            \"object\":
                \"block\",\n            \"type\": \"heading_2\",\n           
                \"heading_2\": {\n                \"rich_text\":
                [\n                    {\n                        \"type\":
                \"text\",\n                        \"text\":
                {\n                            \"content\": \"Lacinato
                kale\"\n                        }\n                   
                }\n                ]\n            }\n        },\n       
                {\n            \"object\": \"block\",\n            \"type\":
                \"paragraph\",\n            \"paragraph\": {\n               
                \"rich_text\": [\n                    {\n                       
                \"type\": \"text\",\n                        \"text\":
                {\n                            \"content\": \"Lacinato kale is a
                variety of kale with a long tradition in Italian cuisine,
                especially that of Tuscany. It is also known as Tuscan kale,
                Italian kale, dinosaur kale, kale, flat back kale, palm tree
                kale, or black Tuscan palm.\",\n                           
                \"link\": {\n                                \"url\":
                \"https://en.wikipedia.org/wiki/Lacinato_kale\"\n                           
                }\n                        }\n                   
                }\n                ]\n            }\n        }\n    ]\n}"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer secret_t1CdN9S8yicG5eWLUOfhcWaOscVnFXns
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: Notion-Version
          in: header
          schema:
            type: string
          example: '{{NOTION_VERSION}}'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
  /v1/pages/{id}:
    get:
      tags:
        - Pages
      summary: Retrieve a page
      description: >-
        Retrieves a Page object using the ID in the request path. This endpoint
        exposes page properties, not page content. 
      parameters:
        - name: Notion-Version
          in: header
          schema:
            type: string
          example: '{{NOTION_VERSION}}'
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: '{{PAGE_ID}}'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                object: page
                id: c4d39556-6364-46a1-8a61-ebbb668f7445
                created_time: '2021-04-27T20:38:00.000Z'
                last_edited_time: '2022-03-02T05:22:00.000Z'
                created_by:
                  object: user
                  id: 6794760a-1f15-45cd-9c65-0dfe42f5135a
                last_edited_by:
                  object: user
                  id: 92a680bb-6970-4726-952b-4f4c03bff617
                cover: null
                icon:
                  type: emoji
                  emoji: 📕
                parent:
                  type: page_id
                  page_id: c1218692-102d-4b47-ab38-c21900b3557b
                archived: false
                properties:
                  title:
                    id: title
                    type: title
                    title:
                      - type: text
                        text:
                          content: Reading List
                          link: null
                        annotations:
                          bold: false
                          italic: false
                          strikethrough: false
                          underline: false
                          code: false
                          color: default
                        plain_text: Reading List
                        href: null
                url: >-
                  https://www.notion.so/Reading-List-c4d39556636446a18a61ebbb668f7445
    patch:
      tags:
        - Pages
      summary: Archive a page
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                archived: true
      parameters:
        - name: Notion-Version
          in: header
          schema:
            type: string
          example: '{{NOTION_VERSION}}'
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: '{{PAGE_ID}}'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                object: block
                id: 2646ac0d-df90-4bab-bb4e-75e3cb972ed1
                created_time: '2022-02-24T22:14:00.000Z'
                last_edited_time: '2022-02-24T22:15:00.000Z'
                created_by:
                  object: user
                  id: 6794760a-1f15-45cd-9c65-0dfe42f5135a
                last_edited_by:
                  object: user
                  id: 92a680bb-6970-4726-952b-4f4c03bff617
                has_children: false
                archived: true
                type: child_page
                child_page:
                  title: ''
  /v1/pages/{page_id}/properties/{property_id}:
    get:
      tags:
        - Pages
      summary: Retrieve a page property item
      parameters:
        - name: Notion-Version
          in: header
          schema:
            type: string
          example: '{{NOTION_VERSION}}'
        - name: page_id
          in: path
          schema:
            type: string
          required: true
          example: '{{PAGE_ID}}'
        - name: property_id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                object: property_item
                type: select
                select:
                  id: 5c944de7-3f4b-4567-b3a1-fa2c71c540b6
                  name: ⭐️⭐️⭐️⭐️⭐️
                  color: default
  /v1/blocks/{id}/children:
    get:
      tags:
        - Blocks
      summary: Retrieve block children
      parameters:
        - name: Notion-Version
          in: header
          schema:
            type: string
          example: '{{NOTION_VERSION}}'
        - name: page_size
          in: query
          schema:
            type: integer
          example: '100'
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: '{{PAGE_ID}}'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              
    patch:
      tags:
        - Blocks
      summary: Append block children
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer secret_t1CdN9S8yicG5eWLUOfhcWaOscVnFXns
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: Notion-Version
          in: header
          schema:
            type: string
          example: '{{NOTION_VERSION}}'
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: '{{PAGE_ID}}'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                object: block
                id: a1712d54-53e4-4893-a69d-4d581cd2c845
                created_time: '2021-04-27T20:38:19.437Z'
                last_edited_time: '2021-05-12T06:07:37.724Z'
                has_children: true
                type: child_page
                child_page:
                  title: 'Who Will Teach Silicon Valley to Be Ethical? '
  /v1/blocks/{id}:
    patch:
      tags:
        - Blocks
      summary: Update a block
      description: >-
        This endpoint allows you to update block content. [See Full
        Documentation](https://developers.notion.com/reference/update-a-block)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                paragraph:
                  rich_text:
                    - type: text
                      text:
                        content: hello to you
      parameters:
        - name: Notion-Version
          in: header
          schema:
            type: string
          example: '{{NOTION_VERSION}}'
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: '{{BLOCK_ID}}'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              
    get:
      tags:
        - Blocks
      summary: Retrieve a block
      parameters:
        - name: Notion-Version
          in: header
          schema:
            type: string
          example: '{{NOTION_VERSION}}'
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: '{{BLOCK_ID}}'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              
    delete:
      tags:
        - Blocks
      summary: Delete a block
      parameters:
        - name: Notion-Version
          in: header
          schema:
            type: string
          example: '{{NOTION_VERSION}}'
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: '{{BLOCK_ID}}'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
  /v1/search:
    post:
      tags:
        - Search
      summary: Search
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: >-
                "{\n    \"query\": \"Media Article\",\n    \"sort\": {\n       
                \"direction\": \"ascending\",\n        \"timestamp\":
                \"last_edited_time\"\n    }\n}"
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: Notion-Version
          in: header
          schema:
            type: string
          example: '{{NOTION_VERSION}}'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
  /v1/comments:
    get:
      tags:
        - Comments
      summary: Retrieve comments
      description: Retrieve a user object using the ID specified in the request path.
      parameters:
        - name: Notion-Version
          in: header
          schema:
            type: string
          example: '{{NOTION_VERSION}}'
        - name: block_id
          in: query
          schema:
            type: string
          example: '{{BLOCK_ID}}'
        - name: page_size
          in: query
          schema:
            type: integer
          example: '100'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              
    post:
      tags:
        - Comments
      summary: Add comment to discussion
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: >-
                "{\n    \"discussion_id\": \"{{DISCUSSION_ID}}\",\n   
                \"rich_text\": [\n        {\n            \"text\":
                {\n                \"content\":
                \"https://www.healthline.com/nutrition/10-proven-benefits-of-kale\",\n               
                \"link\": {\n                    \"type\":
                \"url\",\n                    \"url\":
                \"https://www.healthline.com/nutrition/10-proven-benefits-of-kale\"\n               
                }\n            }\n        }\n    ]\n}"
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: Notion-Version
          in: header
          schema:
            type: string
          example: '{{NOTION_VERSION}}'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
